name: Deploy to Azure VPS

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  deploy:
    runs-on: windows-latest

    env:
      AZURE_SERVER: ${{ secrets.DEPLOY_USERNAME }}
      AZURE_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      AZURE_IP_ADDRESS: "20.102.70.250" # Replace with your VPS IP address or hostname

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure
        run: |
          # Use PowerShell to deploy your code to Azure here
          # Use the $env:AZURE_IP_ADDRESS variable to specify the destination IP address or hostname
          $destination = "\\$env:AZURE_IP_ADDRESS\C$\goodplays\api"
          Copy-Item -Path .\ -Destination $destination -Recurse -Force

      # Add additional steps as needed
